# Generated by Django 5.1.3 on 2025-01-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0004_delete_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tehnic_file',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
    ]
